In [1]:
import numpy as np
n=np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
n=np.arange(12).reshape(4,3)
print(n)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [3]:
n=np.arange(24).reshape(2,3,4)
print(n)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [3]:
n=np.arange(12).reshape(4,3)
print(n)
print()
print(n[1:3]) # first row,second column
print(n[0:4,2])
print(n[0:4,2:4])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[3 4 5]
 [6 7 8]]
[ 2  5  8 11]
[[ 2]
 [ 5]
 [ 8]
 [11]]


https://numpy.org/doc/stable/user/absolute_beginners.html

In [2]:
#2d array
arr=np.array([[1,2,3],[1,2,3]])
print(arr)

[[1 2 3]
 [1 2 3]]
