In [1]:
import numpy
import numpy as np
from numpy import arange
from numpy import *
n = numpy.arange(11)
print(type(n))
print(n)
print(n[0])

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]
0


In [2]:
#example 1d
n = numpy.arange(12)
d = n.reshape(3,4) # 3 -> rows or 4 -> cols
print(type(d))
print(d)

#example 2d
n = numpy.arange(12).reshape(4,3)
print(n)


#example 3d
n = numpy.arange(24).reshape(1,6,4) # 3-> rows or 4 -> cols
print(n)

<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [4]:
n = numpy.arange(12).reshape(4,3)
print(n)
print(n[0:4:,2]) # first row or second cols
print(n[0:4,2:4]) # first row or second cols
print(n[:,-1])


n = numpy.arange(12).reshape(4,3)
print(n)
print(n[1:3,1:2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 2  5  8 11]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[ 2  5  8 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4]
 [7]]


In [5]:
import numpy as np
# # list 1d
l = [1,2,3]
print(l)

# # array 1d
arr = np.array(l)
print(arr)

# 2d example

import numpy as np
# 2d list
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0]) # [1,2,3] -> 1row
print(l[0][0]) # [1,2,3] -> 1row -> first element -> 1

# question list value 4 -> 100
l[1][0] = 100
print(l[1])

# 2d array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0]) # [1,2,3] -> 1 row
print(arr[0][0]) # [1,2,3] -> 1row -> first element -> 1

# question array value 4 -> 100
arr[1][0] = 100
print(arr[1])

[1, 2, 3]
[1 2 3]
[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
[100, 5, 6]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[100   5   6]


In [6]:
# list
l = [1,2,3]
lm = l*2
print(lm)

# array
import numpy as np
arr = np.array(l)
arrM = arr*2
print(arrM)
     

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [7]:
# array running timing less than list
import numpy as np
import time

# list range(10) -> 0 to 9
start = time.time()
l = [i*500 for i in range(1000000)]
print("list output:",time.time() - start) # 0.06

# array
start = time.time()
arr = np.array(1000000)*500
print("array output:",time.time() - start) # 0.0001

list output: 0.07637739181518555
array output: 0.00010013580322265625


In [8]:
# zeros array 1d
import numpy as np
arr =  np.zeros(5)
print(arr)

# zeros array 2d
arr1 = np.zeros((3,4))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# ones array 1d
import numpy as np
arr = np.ones(5)
print(arr)
# ones array 2d
arr1 = np.ones((3,4))
print(arr1)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
import numpy as np
# question zeros -> 2d array -> 10
arr = np.zeros((2,3))+10
print(arr)
# question ones -> 2d array -> 5
arr1 = np.ones((2,3))+5
print(arr1)

# full for 1d
import numpy as np
arr = np.full((3),5)
print(arr)


# full for 2d
import numpy as np
arr1 = np.full((2,3),5)
print(arr1)

[[10. 10. 10.]
 [10. 10. 10.]]
[[6. 6. 6.]
 [6. 6. 6.]]
[5 5 5]
[[5 5 5]
 [5 5 5]]


In [11]:
#random for 1d 0 -> 1
import numpy as np
arr = np.random.random(5)
print(arr)

# random for 2d 0-> 1
arr1 = np.random.random((2,3))
print(arr1)

[0.82624855 0.05351348 0.85476007 0.08494489 0.34209108]
[[0.14042181 0.10992626 0.57287778]
 [0.27136462 0.60348777 0.77762461]]


In [12]:
#arange for 1d
import numpy as np
arr = np.arange(5)
print(arr)

#arange for 1d || to convert into 2d -> reshape
arr1 = np.arange(0,10,2) # start,stop,step
print(arr1)

[0 1 2 3 4]
[0 2 4 6 8]


In [13]:
import numpy as np
# vector 1d list
l = [1,2,3]
print(l)
#vector 1d array
arr = np.array(l)
print(arr)

#matrix 2d list
l = [[1,2,3],[4,5,6]]
print(l)
#matrix 2d array
arr = np.array(l)
print(arr)

#tensor 3d list
l = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(l)
#tensor 3d array
arr = np.array(l)
print(arr)

[1, 2, 3]
[1 2 3]
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
# array
import numpy as np
arr = np.arange(12) # 1d
# arr = np.arange(12).reshape(3,4) # 3 X 4 => 12  # 2d
print("shape: ",arr.shape)
print("shape: ",np.shape(arr))
print("dimension: ",np.ndim(arr))
print("size: ",np.size(arr))
print("datatype: ",arr.dtype)

shape:  (12,)
shape:  (12,)
dimension:  1
size:  12
datatype:  int64


In [15]:
#reshape array
import numpy as np
arr = np.arange(12) # 12 -> 3*4 || 12 -> 4*3
up_arr = np.reshape(arr,(3,4)) # 3 -> row || 4 -> cols
print(up_arr)

# example 2d
arr1 = np.arange(24)
up_arr1 = np.reshape(arr1,(12*2))
print(up_arr1)

# example 3d
arr2 = np.arange(24)
up_arr2 = np.reshape(arr2,(3*2*4))
print(up_arr2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [17]:
#flatten -> create copy then works
import numpy as np
#example 2d
arr = np.arange(12).reshape(3,4)
print(arr)
up_arr = arr.flatten()
print(up_arr)
print(arr)

#example 3d
arr1 = np.arange(24).reshape(3,2,4)
print(arr1)
up_arr1 = arr1.flatten()
print(up_arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [18]:
#ravel -> works on original array
import numpy as np
# example 2d
arr = np.arange(14).reshape(7,2)
print(arr)
up_arr = arr.ravel()
up_arr[0] = 100
print(up_arr)
print(arr)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13]
[[100   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]
 [ 10  11]
 [ 12  13]]


In [19]:
# transpose
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)
up_arr = arr.T
print(up_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
#slicing for 1d
import numpy as np
arr = np.arange(11)
print(arr)
up_arr = arr[:3]
print(up_arr)

#slicing for 2d
import numpy as np
arr1 = np.arange(16).reshape(8,2)
print(arr1)
up_arr1 = arr1[:,-1]
print(up_arr1)

#slicing for 3d -> arange(24) -> 0,23
import numpy as np
arr2 = np.arange(24).reshape(3,4,2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[ 1  3  5  7  9 11 13 15]
