**Sort**

In [31]:
#1d
import numpy as np
arr=np.array([10,5,20,30,9,8,7])
print(arr)
print("Sorted ascending:",np.sort(arr))
print("Sorted descending:",np.sort(arr)[::-1])

arr2=np.array([[2,9],[10,1]])
print("Sorted row wise:\n",np.sort(arr2,axis=1)) #by default sort is row wise i.e. axis 1
print("Sorted column wise:\n",(np.sort(arr2,axis=0)))
print("Sorting ascending:\n",np.sort(np.sort(arr2,axis=0)))
print("Sorting descending:\n", np.sort(np.sort(arr2, axis=0))[::-1, ::-1])

[10  5 20 30  9  8  7]
Sorted ascending: [ 5  7  8  9 10 20 30]
Sorted descending: [30 20 10  9  8  7  5]
Sorted row wise:
 [[ 2  9]
 [ 1 10]]
Sorted column wise:
 [[ 2  1]
 [10  9]]
Sorting ascending:
 [[ 1  2]
 [ 9 10]]
Sorting descending:
 [[10  9]
 [ 2  1]]


In [27]:
#filter
arr=np.array([10,20,30,40])
print(arr)
print(arr[arr<=20])

[10 20 30 40]
[10 20]


In [32]:
#Fancy indexing / BOOLEAN INDEXING
import numpy as np
arr = np.array([10,20,3,4,5,90,88,30])
print(arr)
arr_Fancy = arr[[0,2]]
print(arr_Fancy)

[10 20  3  4  5 90 88 30]
[10  3]


In [44]:
#np.where
import numpy as np

arr = np.array([10,3,4,9,5,20,30,70,55])
print(arr)
arrW = np.where(arr>40,arr,"")
print(arrW)
arrW = np.where(arr>40,arr+2,arr-2)
print(arrW)

[10  3  4  9  5 20 30 70 55]
['' '' '' '' '' '' '' '70' '55']
[ 8  1  2  7  3 18 28 72 57]


In [48]:
#Concatenation: adding is not same as concatenation
import numpy as np
arr=np.array([10,20,30])
brr=np.array([1,2,3])
print("Concatenated:\n", np.concatenate((arr, brr)))

a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])
print("Concatenated:\n", np.concatenate((a, b),axis=1))


Concatenated:
 [10 20 30  1  2  3]
Concatenated:
 [[10 20  1  2]
 [30 40  3  4]]


In [ ]:
import numpy as np

arr = np.array([10,3,4,9,5,20,30,70,55])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr),np.argmin(arr))
print(np.max(arr),np.argmax(arr))
print(np.var(arr))
print(np.std(arr))

"""
1. np.sum(a) -> Sum of all elements
2. np.mean(a) -> Average = Sum of elements / Number of elements
3. np.median(a) -> Middle value after sorting
4. np.min(a) -> Smallest value in array
5. np.max(a) -> Largest value in array
6. np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
7. np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
8. np.prod(a) -> Multiplication of all elements
9. np.cumsum(a) -> Cumulative (running) sum
10. np.cumprod(a) -> Cumulative (running) product
11. np.argmin(a) -> Index position of minimum value
12. np.argmax(a) -> Index position of maximum value
13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
14. np.unique(a) -> Returns unique values only -> Removes duplicates
15. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
17. np.ptp(a) -> Range = Max - Min
18. np.any(a) -> True if at least one value is True

"""

206
22.88888888888889
10.0
3 1
70 7
526.7654320987655
22.951371028737377


'\n1. np.sum(a) -> Sum of all elements\n2. np.mean(a) -> Average = Sum of elements / Number of elements\n3. np.median(a) -> Middle value after sorting\n4. np.min(a) -> Smallest value in array\n5. np.max(a) -> Largest value in array\n6. np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length\n7. np.std(a) -> Standard Deviation = √Variance -> Measures spread of data\n8. np.prod(a) -> Multiplication of all elements\n9. np.cumsum(a) -> Cumulative (running) sum\n10. np.cumprod(a) -> Cumulative (running) product\n11. np.argmin(a) -> Index position of minimum value\n12. np.argmax(a) -> Index position of maximum value\n13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)\n14. np.unique(a) -> Returns unique values only -> Removes duplicates\n15. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median\n16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%\n17. np.ptp(a) -> Range = Max - Min\n18. np