Handling Missing Values

In [6]:
import pandas as pd
import numpy as np
data = {
    "colors":['red','green','blue','orange','green','blue',np.nan]
}
df = pd.DataFrame(data)
print(df)

   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
6     NaN


Handle null values

In [7]:
df.dropna(inplace=True)
print(df)

   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue


Label Encoding

In [17]:
from sklearn.preprocessing import LabelEncoder as le
df['color_encoder'] = le().fit_transform(df['colors'])
print(df)

# or
# from sklearn.preprocessing import LabelEncoder
# le=LabelEncoder()
# df['color_encoder'] = le.fit_transform(df['colors'])
# print(df)

# or
# import sklearn
# df['color_encoder'] = sklearn.preprocessing.LabelEncoder().fit_transform(df['colors'])
# print(df)

   colors  color_encoder
0     red              3
1   green              1
2    blue              0
3  orange              2
4   green              1
5    blue              0


One Hot Encoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# one hot encoding (by the help of sklearn)
ohe = OneHotEncoder()
encoded = ohe.fit_transform(df[['colors' ]])
print (encoded.toarray(),'\n\n')

encoder_df =pd.get_dummies(df.colors)
print(encoder_df)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 


    blue  green  orange    red
0  False  False   False   True
1  False   True   False  False
2   True  False   False  False
3  False  False    True  False
4  False   True   False  False
5   True  False   False  False


In [33]:
# combination of handle missing value | label encoding | onehot encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

data = {
"age": [10,20,np.nan, 26, 30],
"gender": ['male', 'female', 'others', 'male',np.nan],
"name": ['dheeraj ', 'kavi', 'sapu', 'yash', 'hello']
}
df = pd.DataFrame(data)

# handle missing values
df['age' ] = df['age'].fillna(df['age'].mean())
df.dropna(subset=['gender'], inplace=True)
print(df,'\n\n')

# label encoding
le = LabelEncoder()
df['gender_label_encoded'] = le.fit_transform(df['gender'])
print(df,'\n\n')

#one hot encoding
oe = OneHotEncoder()
oe_e = oe.fit_transform(df[['gender']]).toarray()
print('One Hot Encoder\n',oe_e,'\n\n')

    age  gender      name
0  10.0    male  dheeraj 
1  20.0  female      kavi
2  21.5  others      sapu
3  26.0    male      yash 


    age  gender      name  gender_label_encoded
0  10.0    male  dheeraj                      1
1  20.0  female      kavi                     0
2  21.5  others      sapu                     2
3  26.0    male      yash                     1 


One Hot Encoder
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] 


